pipeline{
    agent any
    stages{
        stage("Call another job"){
            steps{
                build job: 'upstream-job', parameters: [
                    string(name: 'username', value: 'Harshal')
                ]
            }
        }

        stage("Completion"){
            steps{
                echo "Upstream job is complete!"
            }
        }
    }
}