pipeline{
    agent any
    stages{
        stage("Call another job"){
            steps{
                def userName = input(
                    id: 'userName', message: 'Please provide username', parameters: [
                        string(name: 'userName', defaultValue: 'Nihal', description: 'Your username')
                    ]
                )

                //call the upstream job
                build job: 'upstream-job', parameters: [
                    string(name: 'username', value: userName)
                ]
            }
        }

        stage("Completion"){
            steps{
                echo "Upstream job is complete!"
            }
        }
    }
}