pipeline{
    agent any
    stages{
        stage("Git checkout"){
            steps{
                git branch: 'main', changelog: false, credentialsId: 'prod-repo-creds', poll: false, url: 'https://github.com/nihal-2059/jenkins-docker-test.git'
            }
        }

        stage("Build Image"){
            steps{
                sh "docker build -t nihals/nginx:v${env.BUILD_NUMBER} ."
            }
        }

        stage("Push to Repository"){
            steps{
                script{
                    withDockerRegistry(credentialsId: 'docker-creds', url: 'https://index.docker.io/v1/') {
                        def image = docker.image("nihals/nginx:v${env.BUILD_NUMBER}")
                        image.push()
                    }
                }
            }
        }
    }
post {
    success {
        echo "Image has been pushed successfully!"
    }

    failure {
        echo "Stage failed, please check!"
    }
}
}