pipeline{
    agent any
    stages{
        stage("Build Stage"){
            steps{
                echo "Build Started.."
            }
        }

        stage("Test Stage"){
            steps{
                echo0 "Test Started.."
            }
        }

        stage("Deploy Stage"){
            steps{
                echo "Deploy Started.."
            }
        }
    }
//post build actions
post {
    //if all the builds succeded.
    success {
        echo "The stages were completed successfully!"
    }
    //if any one of the build fails
    failure {
        echo "Stages have failed, please check once"
    }
}
}