@Library("basicFunction") _
pipeline{
    agent any
    stages{
        stage('Clone Repository'){
            steps{
                //git branch: 'main', changelog: false, poll: false, url: 'https://github.com/nihal-dev/argocd-practise.git'
                gitClone.cloneRepo() //shared library file present in vars
            }
        }

        stage('check the pwd'){
            steps{
                sh "pwd"
            }
        }

        stage('Display file contents'){
            //parallel job details
            parallel{
                stage('Display deployment file'){
                    steps{
                        sh "cat yaml/nginx-deploy.yaml"
                    }
                }

                stage('Display service file'){
                    steps{
                        sh "cat yaml/nginx-service.yaml"
                    }
                }
            }
        }

        stage('Display Bye message'){
            steps{
                echo "Bye"
            }
        }
    }
}