pipeline{
    agent any
    stages{
        stage('Clone Repository'){
            steps{
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/nihal-dev/argocd-practise.git'
            }
        }

        stage('Check the contents of file'){
            steps{
                sh "cat yaml/nginx-service.yaml"
            }
        }
    }
}