pipeline{
    agent any
    parameters{
        string(name: "USERID", defaultValue: "nihal" ,description: "Give your username")
    }
    stages{
        stage('Display the values'){
            steps{
            echo "${params.USERID}"
            }
        }
    }
}