pipeline{
    agent any
    stages{
        stage("Take user input"){
            steps{
                script{
                    def userInput = input(
                        id: 'userInput', message: 'Please provide inputs',
                        parameters: [string(name: 'user_name', defaultValue: 'nihal', description: 'Your username')]
                    )
                    //def userName = userInput['user_name']
                    echo "Username is ${userInput}"
                }
            }
        }
    }
}
